TestDbt:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: Ru123456
      dbname: postgres
      schema: stage

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: Ru123456
      dbname: postgres
      schema: stage_prod

  target: dev